[package]
name = "simple"
version = "0.1.0"
authors = ["Josh McKinney <joshka@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
